# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_Finished',
            new_name='is_finished',
        ),
    ]
