# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0004_auto_20171214_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
